#!/bin/sh

a=/etc/hotplug2.rules
b=/rom/etc/hotplug2.rules
c=/jffs/custom/hotplug2.rules
d=$c.md5

# Create the custom folder
mkdir -p "/jffs/custom"

# Check the hash
if ! md5sum -cs $d;
then
        # Hash the file
        echo "Hashing " $b >> /tmp/syslog.log
        md5sum $b > $d
        echo "Cloning and modifying " $b >> /tmp/syslog.log
        sed '/^exec \/sbin\/asus_lp.*/a exec \/jffs\/scripts\/restart_printer ;'
fi

# Compare the symbolic link
r=$(readlink -f $a)
if [ $r != $c ]
then
	# Replace hotplug2 rules with our own, and restart hotplug2
	echo "Replacing symbolic link for hotplug2" >> /tmp/syslog.log
	ln -sf $c $a
	killall hotplug2
fi
